# Generated by Django 6.0.1 on 2026-02-06 10:02

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cinema',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('nom', models.CharField(max_length=200)),
                ('adresse', models.CharField(max_length=200)),
                ('ville', models.CharField(max_length=200)),
            ],
            options={
                'verbose_name': 'Cinéma',
                'verbose_name_plural': 'Cinemas',
                'indexes': [models.Index(fields=['nom'], name='cinema_mana_nom_d0dbea_idx')],
            },
        ),
    ]
