# Generated by Django 6.0.1 on 2026-01-30 11:29

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cinema_manager', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Salle',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('numero', models.PositiveIntegerField()),
                ('capacite', models.PositiveIntegerField()),
                ('type_ecran', models.CharField(choices=[('STD', 'Standard'), ('IMAX', 'IMAX'), ('3D', 'Real 3D'), ('4DX', '4DX')], default='STD', max_length=20)),
                ('cinema', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cinemas', to='cinema_manager.cinema')),
            ],
            options={
                'indexes': [models.Index(fields=['numero'], name='salle_manag_numero_09a553_idx')],
            },
        ),
    ]
