# Generated by Django 6.0.1 on 2026-02-06 10:02

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('film_manager', '0001_initial'),
        ('salle_manager', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Seance',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('date_heure', models.DateTimeField()),
                ('prix', models.DecimalField(decimal_places=2, max_digits=6)),
                ('film', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seances', to='film_manager.film')),
                ('salle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seances', to='salle_manager.salle')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
