# Generated by Django 6.0.1 on 2026-01-30 14:14

import django.core.validators
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('account', '0001_initial'),
        ('seance_manager', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('date_reservation', models.DateTimeField(auto_now_add=True)),
                ('nb_places', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservations', to='account.client')),
                ('seance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservations', to='seance_manager.seance')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
