# Generated by Django 6.0.1 on 2026-02-06 10:02

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Film',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('titre', models.CharField(max_length=255)),
                ('duree', models.PositiveIntegerField(help_text='Durée en minutes')),
                ('genre', models.CharField(max_length=255)),
                ('realisateur', models.CharField(max_length=255)),
                ('synopsis', models.TextField()),
                ('affiche', models.ImageField(blank=True, null=True, upload_to='media/films/')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
