# Generated by Django 6.0.1 on 2026-01-30 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Film',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tire', models.CharField(max_length=255)),
                ('duree', models.PositiveIntegerField(help_text='Durée en munites')),
                ('genre', models.CharField(max_length=255)),
                ('realisateur', models.CharField(max_length=255)),
                ('synopsis', models.TextField()),
                ('affiche', models.ImageField(blank=True, null=True, upload_to='films/')),
            ],
        ),
    ]
